// ITパスポート 頻出用語（シラバス6.3〜6.5の頻出＋混同しやすい語を中心に収録）
// importance: 出題されやすさの目安（独自推定）
window.ITPASS_TERMS = [
  // ===== テクノロジ系 =====
  { id: "cpu", term: "CPU", reading: "シーピーユー", field: "テクノロジ", category: "コンピュータ構成要素", importance: 98, def: "コンピュータの演算・制御を担う処理装置。プログラムの命令を解釈して実行する。", tip: "「頭脳」。クロック周波数やコア数が性能の目安。", pair: "gpu" },
  { id: "gpu", term: "GPU", reading: "ジーピーユー", field: "テクノロジ", category: "コンピュータ構成要素", importance: 72, def: "画像処理に特化したプロセッサ。並列計算が得意で、AIの学習・推論にも使われる。", tip: "CPUが汎用、GPUが並列特化。", pair: "cpu" },
  { id: "ram", term: "RAM", reading: "ラム", field: "テクノロジ", category: "コンピュータ構成要素", importance: 95, def: "主記憶装置。電源を切ると内容が消える揮発性メモリ。作業中のデータを置く。", tip: "「今使っている机」。ROMは電源を切っても残る。", pair: "rom" },
  { id: "rom", term: "ROM", reading: "ロム", field: "テクノロジ", category: "コンピュータ構成要素", importance: 88, def: "電源を切っても内容が残る不揮発性メモリ。ファームウェアなどの固定データを格納する。", tip: "Read Only Memory。書き換えできない／しにくい。", pair: "ram" },
  { id: "cache", term: "キャッシュメモリ", reading: "", field: "テクノロジ", category: "コンピュータ構成要素", importance: 90, def: "CPUと主記憶の速度差を埋める高速な小容量メモリ。よく使うデータを一時保管する。", tip: "「手元のメモ」。バッファは速度差の吸収（待ち行列）のニュアンス。", pair: "buffer" },
  { id: "buffer", term: "バッファ", reading: "", field: "テクノロジ", category: "コンピュータ構成要素", importance: 78, def: "処理速度の違う装置間でデータを一時的に蓄えて、待ちを吸収する領域。", tip: "キャッシュ＝再利用、バッファ＝速度差の吸収。", pair: "cache" },
  { id: "ssd", term: "SSD", reading: "エスエスディー", field: "テクノロジ", category: "ハードウェア", importance: 82, def: "フラッシュメモリを使った補助記憶装置。HDDより高速・静音・耐衝撃。", tip: "Solid State Drive。可動部品がない。", pair: "hdd" },
  { id: "hdd", term: "HDD", reading: "エイチディーディー", field: "テクノロジ", category: "ハードウェア", importance: 80, def: "磁気ディスクでデータを記録する補助記憶装置。大容量・低単価だが機械的に弱い。", tip: "Hard Disk Drive。ヘッドとプラッタが回転する。", pair: "ssd" },
  { id: "os", term: "OS", reading: "オーエス", field: "テクノロジ", category: "ソフトウェア", importance: 96, def: "ハードウェアを管理し、アプリケーションに共通機能を提供する基本ソフトウェア。", tip: "Windows、macOS、Linux、iOS、Androidなど。", pair: null },
  { id: "middleware", term: "ミドルウェア", reading: "", field: "テクノロジ", category: "ソフトウェア", importance: 74, def: "OSとアプリケーションの間に位置し、DBや通信などの共通機能を提供するソフトウェア。", tip: "「間」にいる。DBMSは代表例。", pair: null },
  { id: "virtualization", term: "仮想化", reading: "かそうか", field: "テクノロジ", category: "システム構成要素", importance: 88, def: "1台の物理コンピュータ上で複数の仮想コンピュータを動かす技術。資源を効率利用する。", tip: "ハイパーバイザが仮想マシンを制御する。", pair: "container" },
  { id: "container", term: "コンテナ", reading: "", field: "テクノロジ", category: "システム構成要素", importance: 76, def: "アプリとその実行環境をひとまとめにして、どこでも同じように動かす仕組み。", tip: "Dockerが代表。VMより軽量。", pair: "virtualization" },
  { id: "cloud", term: "クラウドコンピューティング", reading: "", field: "テクノロジ", category: "システム構成要素", importance: 94, def: "インターネット経由で、サーバやストレージなどのIT資源を必要なときに使う形態。", tip: "所有から利用へ。従量課金が基本。", pair: null },
  { id: "saas", term: "SaaS", reading: "サース", field: "テクノロジ", category: "システム構成要素", importance: 92, def: "Software as a Service。完成したソフトウェアをネット経由で利用する形態。", tip: "例: Gmail、Slack、Salesforce。使うだけ。", pair: "paas" },
  { id: "paas", term: "PaaS", reading: "パース", field: "テクノロジ", category: "システム構成要素", importance: 86, def: "Platform as a Service。アプリ開発・実行環境を提供する形態。", tip: "OSやミドルウェアは提供側が管理。開発に集中。", pair: "iaas" },
  { id: "iaas", term: "IaaS", reading: "イアース", field: "テクノロジ", category: "システム構成要素", importance: 86, def: "Infrastructure as a Service。仮想サーバやストレージなど基盤を提供する形態。", tip: "OSより上は利用者が管理。自由度が高い。", pair: "saas" },
  { id: "lan", term: "LAN", reading: "ラン", field: "テクノロジ", category: "ネットワーク", importance: 96, def: "同じ建物や敷地内など、比較的狭い範囲のネットワーク。", tip: "Local Area Network。社内ネットのイメージ。", pair: "wan" },
  { id: "wan", term: "WAN", reading: "ワン", field: "テクノロジ", category: "ネットワーク", importance: 92, def: "地理的に離れた拠点同士を結ぶ広域ネットワーク。", tip: "Wide Area Network。本社と支社をつなぐ。", pair: "lan" },
  { id: "vlan", term: "VLAN", reading: "ブイラン", field: "テクノロジ", category: "ネットワーク", importance: 80, def: "物理的な配線に関係なく、論理的にLANを分割する技術。", tip: "部署ごとに通信を分離できる。", pair: "vpn" },
  { id: "vpn", term: "VPN", reading: "ブイピーエヌ", field: "テクノロジ", category: "ネットワーク", importance: 93, def: "公衆網の上に仮想的な専用回線を作り、安全に通信する技術。", tip: "在宅勤務で社内システムに入るときに使う。", pair: "vlan" },
  { id: "tcpip", term: "TCP/IP", reading: "ティーシーピーアイピー", field: "テクノロジ", category: "ネットワーク", importance: 90, def: "インターネットの標準通信プロトコル群。信頼性のある通信とアドレス付けを担う。", tip: "TCPは接続型・信頼性、UDPは高速・非接続。", pair: "udp" },
  { id: "udp", term: "UDP", reading: "ユーディーピー", field: "テクノロジ", category: "ネットワーク", importance: 78, def: "コネクションレスで高速な通信プロトコル。到達確認をしない。", tip: "動画配信や音声通話向き。欠落より遅延を嫌う。", pair: "tcpip" },
  { id: "dns", term: "DNS", reading: "ディーエヌエス", field: "テクノロジ", category: "ネットワーク", importance: 88, def: "ドメイン名とIPアドレスを相互に変換する仕組み。", tip: "名前解決。www.example.com → 数字の住所。", pair: null },
  { id: "http", term: "HTTP / HTTPS", reading: "", field: "テクノロジ", category: "ネットワーク", importance: 90, def: "Webページをやり取りするプロトコル。HTTPSは暗号化されたHTTP。", tip: "SはSecure。鍵マークがHTTPS。", pair: null },
  { id: "rdb", term: "関係データベース", reading: "かんけいデータベース", field: "テクノロジ", category: "データベース", importance: 92, def: "表（テーブル）の集まりでデータを管理し、SQLで操作するデータベース。", tip: "行＝レコード、列＝フィールド（属性）。", pair: null },
  { id: "sql", term: "SQL", reading: "エスキューエル", field: "テクノロジ", category: "データベース", importance: 88, def: "関係データベースを操作するための言語。検索・追加・更新・削除ができる。", tip: "SELECTが検索。PRIMARY KEYで一意に識別。", pair: null },
  { id: "primarykey", term: "主キー", reading: "しゅキー", field: "テクノロジ", category: "データベース", importance: 84, def: "表の中で各行を一意に識別するための列。重複もNULLも許されない。", tip: "社員番号のような「その人だけ」の番号。", pair: "foreignkey" },
  { id: "foreignkey", term: "外部キー", reading: "がいぶキー", field: "テクノロジ", category: "データベース", importance: 80, def: "他の表の主キーを参照する列。表同士の関係をつなぐ。", tip: "注文表の顧客IDが顧客表を指す、など。", pair: "primarykey" },
  { id: "normalization", term: "正規化", reading: "せいきか", field: "テクノロジ", category: "データベース", importance: 82, def: "データの重複を減らし、矛盾が起きにくい形に表を分割すること。", tip: "更新異常を防ぐための設計技術。", pair: null },
  { id: "cia", term: "情報セキュリティの3要素", reading: "CIA", field: "テクノロジ", category: "セキュリティ", importance: 99, def: "機密性（Confidentiality）・完全性（Integrity）・可用性（Availability）。", tip: "漏らさない・改ざんしない・使える。最頻出。", pair: null },
  { id: "confidentiality", term: "機密性", reading: "きみつせい", field: "テクノロジ", category: "セキュリティ", importance: 96, def: "許可された人だけが情報にアクセスできること。", tip: "暗号化やアクセス制御で守る。", pair: "integrity" },
  { id: "integrity", term: "完全性", reading: "かんぜんせい", field: "テクノロジ", category: "セキュリティ", importance: 96, def: "情報が改ざんされず、正確で完全な状態であること。", tip: "ハッシュ値で改ざん検知。", pair: "availability" },
  { id: "availability", term: "可用性", reading: "かようせい", field: "テクノロジ", category: "セキュリティ", importance: 96, def: "必要なときに情報やシステムを使えること。", tip: "冗長化、バックアップ、障害対策。", pair: "confidentiality" },
  { id: "encryption", term: "暗号化", reading: "あんごうか", field: "テクノロジ", category: "セキュリティ", importance: 97, def: "第三者に読めない形に変換すること。鍵を使えば元に戻せる（復号できる）。", tip: "可逆。ハッシュは基本的に不可逆。", pair: "hash" },
  { id: "hash", term: "ハッシュ化", reading: "", field: "テクノロジ", category: "セキュリティ", importance: 94, def: "データを固定長の値に変換する一方通行の処理。元のデータには戻せない。", tip: "パスワード保存や改ざん検知に使う。", pair: "encryption" },
  { id: "publickey", term: "公開鍵暗号", reading: "こうかいかぎあんごう", field: "テクノロジ", category: "セキュリティ", importance: 93, def: "公開鍵と秘密鍵のペアを使う暗号方式。公開鍵で暗号化し、秘密鍵で復号する。", tip: "鍵配送問題を解決。デジタル署名は逆の使い方。", pair: "commonkey" },
  { id: "commonkey", term: "共通鍵暗号", reading: "きょうつうかぎあんごう", field: "テクノロジ", category: "セキュリティ", importance: 90, def: "暗号化と復号に同じ鍵を使う方式。処理は速いが鍵の配送が課題。", tip: "AESが代表。大量データ向き。", pair: "publickey" },
  { id: "digitalsign", term: "デジタル署名", reading: "", field: "テクノロジ", category: "セキュリティ", importance: 91, def: "送信者の秘密鍵で署名し、公開鍵で検証する。なりすましと改ざんを防ぐ。", tip: "「本人が書いた」＋「途中で変わっていない」。", pair: "certificate" },
  { id: "certificate", term: "デジタル証明書", reading: "", field: "テクノロジ", category: "セキュリティ", importance: 86, def: "公開鍵が本物であることを、認証局（CA）が保証する電子的な証明書。", tip: "HTTPSの鍵マークの裏側。", pair: "digitalsign" },
  { id: "authn", term: "認証", reading: "にんしょう", field: "テクノロジ", category: "セキュリティ", importance: 92, def: "「あなたは誰か」を確認すること。パスワード、生体、所有物などで行う。", tip: "Authentication。認可の前工程。", pair: "authz" },
  { id: "authz", term: "認可", reading: "にんか", field: "テクノロジ", category: "セキュリティ", importance: 88, def: "「何をしてよいか」を許可すること。権限の付与。", tip: "Authorization。ログイン後のアクセス権。", pair: "authn" },
  { id: "mfa", term: "多要素認証", reading: "たようそにんしょう", field: "テクノロジ", category: "セキュリティ", importance: 84, def: "知識・所有・生体など、異なる種類の要素を組み合わせて本人確認する方式。", tip: "パスワード＋スマホ通知、など。二段階認証と混同しやすい。", pair: null },
  { id: "malware", term: "マルウェア", reading: "", field: "テクノロジ", category: "セキュリティ", importance: 90, def: "悪意あるソフトウェアの総称。ウイルス、ワーム、トロイの木馬、ランサムウェアなど。", tip: "「悪いソフト全般」。種類名は個別に覚える。", pair: "ransomware" },
  { id: "ransomware", term: "ランサムウェア", reading: "", field: "テクノロジ", category: "セキュリティ", importance: 88, def: "データを暗号化して使用不能にし、解除と引き換えに金銭を要求するマルウェア。", tip: "二重脅迫（ダブルエクストーション）も出題増。", pair: "malware" },
  { id: "phishing", term: "フィッシング", reading: "", field: "テクノロジ", category: "セキュリティ", importance: 86, def: "偽サイトや偽メールで、IDやパスワード、カード番号などをだまし取る攻撃。", tip: "「釣り」。URLをよく見る。", pair: null },
  { id: "ddos", term: "DDoS攻撃", reading: "ディードス", field: "テクノロジ", category: "セキュリティ", importance: 82, def: "多数の端末から一斉にアクセスし、サービスを使えなくする攻撃。可用性を狙う。", tip: "DoSの分散版。ボットネットが使われる。", pair: null },
  { id: "firewall", term: "ファイアウォール", reading: "", field: "テクノロジ", category: "セキュリティ", importance: 88, def: "内外の通信を監視し、許可した通信だけを通す防御壁。", tip: "ネットワークの玄関番。", pair: null },
  { id: "idsips", term: "IDS / IPS", reading: "", field: "テクノロジ", category: "セキュリティ", importance: 80, def: "IDSは不正侵入を検知、IPSは検知して遮断する仕組み。", tip: "SがPrevention＝防ぐ。", pair: null },
  { id: "backup", term: "バックアップ", reading: "", field: "テクノロジ", category: "セキュリティ", importance: 85, def: "障害や災害に備え、データを複製して保管すること。", tip: "3-2-1ルール（3コピー、2媒体、1オフサイト）も覚えると強い。", pair: null },
  { id: "raid1", term: "RAID 1", reading: "レイドワン", field: "テクノロジ", category: "システム構成要素", importance: 78, def: "ミラーリング。同じデータを2台のディスクに書く。耐障害性が高い。", tip: "容量は半分。RAID 0はストライピングで速度重視・耐障害なし。", pair: "raid0" },
  { id: "raid0", term: "RAID 0", reading: "レイドゼロ", field: "テクノロジ", category: "システム構成要素", importance: 74, def: "ストライピング。データを分割して複数ディスクに書き、速度を上げる。", tip: "1台壊れても全体が死ぬ。可用性は下がる。", pair: "raid1" },
  { id: "algorithm", term: "アルゴリズム", reading: "", field: "テクノロジ", category: "基礎理論", importance: 80, def: "問題を解くための手順・計算方法。同じ入力なら同じ結果になるよう定義する。", tip: "フローチャートや擬似言語で表す。", pair: null },
  { id: "flowchart", term: "流れ図（フローチャート）", reading: "", field: "テクノロジ", category: "基礎理論", importance: 76, def: "処理の流れを図形で表したもの。端子・処理・判断などの記号を使う。", tip: "ひし形は条件分岐。", pair: null },
  { id: "genai", term: "生成AI", reading: "せいせいエーアイ", field: "テクノロジ", category: "情報メディア", importance: 92, def: "テキストや画像、コードなどを新たに作り出す人工知能。大規模言語モデルが代表。", tip: "シラバス近年の重点。使い方とリスク両方。", pair: "hallucination" },
  { id: "hallucination", term: "ハルシネーション", reading: "", field: "テクノロジ", category: "情報メディア", importance: 90, def: "生成AIが事実と異なる内容を、もっともらしく出力してしまう現象。", tip: "「幻覚」。根拠確認が必須。", pair: "genai" },
  { id: "prompteng", term: "プロンプトエンジニアリング", reading: "", field: "テクノロジ", category: "情報メディア", importance: 84, def: "生成AIから望ましい出力を得るために、指示文（プロンプト）を設計する技術。", tip: "役割・制約・例示を書くと精度が上がる。", pair: "finetune" },
  { id: "finetune", term: "ファインチューニング", reading: "", field: "テクノロジ", category: "情報メディア", importance: 78, def: "学習済みモデルを、特定用途のデータで追加学習して適応させること。", tip: "ゼロから作らず、既存モデルを調整する。", pair: "prompteng" },
  { id: "iot", term: "IoT", reading: "アイオーティー", field: "テクノロジ", category: "ハードウェア", importance: 86, def: "Internet of Things。モノがネットにつながり、データをやり取りする仕組み。", tip: "センサー＋通信＋クラウドが基本形。", pair: null },

  // ===== マネジメント系 =====
  { id: "pm", term: "プロジェクトマネジメント", reading: "", field: "マネジメント", category: "プロジェクトマネジメント", importance: 94, def: "期限・予算・品質の制約の中で、目的の成果物を生み出すための管理活動。", tip: "日常業務（オペレーション）とは切り分ける。", pair: null },
  { id: "scope", term: "スコープ", reading: "", field: "マネジメント", category: "プロジェクトマネジメント", importance: 82, def: "プロジェクトで実施する作業の範囲。何をやり、何をやらないかの境界。", tip: "スコープクリープ＝範囲が勝手に広がること。", pair: null },
  { id: "wbs", term: "WBS", reading: "ダブリュービーエス", field: "マネジメント", category: "プロジェクトマネジメント", importance: 88, def: "Work Breakdown Structure。成果物や作業を階層的に分解した構成図。", tip: "「何を作るか」を漏れなく洗い出す道具。", pair: "gantt" },
  { id: "gantt", term: "ガントチャート", reading: "", field: "マネジメント", category: "プロジェクトマネジメント", importance: 86, def: "作業を棒グラフで時系列に表した工程表。進捗の見える化に使う。", tip: "いつやるかが分かる。依存関係はアローダイアグラム。", pair: "arrow" },
  { id: "arrow", term: "アローダイアグラム", reading: "", field: "マネジメント", category: "プロジェクトマネジメント", importance: 84, def: "作業の順序と所要日数を矢線で表し、クリティカルパスを求める図。", tip: "最も余裕のない経路＝最短完了日を決める。", pair: "gantt" },
  { id: "criticalpath", term: "クリティカルパス", reading: "", field: "マネジメント", category: "プロジェクトマネジメント", importance: 90, def: "プロジェクト完了までに余裕がゼロの作業経路。ここが遅れると全体が遅れる。", tip: "最長経路。重点管理する。", pair: "arrow" },
  { id: "waterfall", term: "ウォーターフォール", reading: "", field: "マネジメント", category: "開発技術", importance: 90, def: "要件定義→設計→実装→テスト…と工程を順に進める開発モデル。", tip: "計画重視。後工程の手戻りコストが大きい。", pair: "agile" },
  { id: "agile", term: "アジャイル", reading: "", field: "マネジメント", category: "開発技術", importance: 93, def: "短い反復（イテレーション）で動くソフトウェアを作り、変化に対応する開発手法。", tip: "スクラムが代表。顧客協働・変化への適応。", pair: "waterfall" },
  { id: "scrum", term: "スクラム", reading: "", field: "マネジメント", category: "開発技術", importance: 88, def: "アジャイルの代表的枠組み。プロダクトオーナー・スクラムマスター・開発者が役割。", tip: "スプリント、バックログ、デイリースクラム。", pair: "sprint" },
  { id: "sprint", term: "スプリント", reading: "", field: "マネジメント", category: "開発技術", importance: 86, def: "スクラムにおける短期間の開発サイクル。通常1〜4週間。", tip: "終わりにレビューとふりかえり（レトロスペクティブ）。", pair: "scrum" },
  { id: "backlog", term: "プロダクトバックログ", reading: "", field: "マネジメント", category: "開発技術", importance: 80, def: "作る機能や改善項目を優先順位付きで並べた一覧。POが管理する。", tip: "スプリントバックログは「今スプリントでやる分」。", pair: "sprint" },
  { id: "itil", term: "ITIL", reading: "アイティル", field: "マネジメント", category: "サービスマネジメント", importance: 82, def: "ITサービスマネジメントのベストプラクティスをまとめた枠組み。", tip: "インシデント、問題、変更などのプロセスが頻出。", pair: "incident" },
  { id: "incident", term: "インシデント", reading: "", field: "マネジメント", category: "サービスマネジメント", importance: 90, def: "サービスの中断や品質低下を引き起こす、または引き起こす可能性のある出来事。", tip: "まず復旧が目的。原因究明は「問題管理」。", pair: "problem" },
  { id: "problem", term: "問題（プロブレム）", reading: "", field: "マネジメント", category: "サービスマネジメント", importance: 86, def: "インシデントの原因。根本原因を特定し、再発を防ぐ対象。", tip: "インシデント＝症状、問題＝病名。", pair: "incident" },
  { id: "sla", term: "SLA", reading: "エスエルエー", field: "マネジメント", category: "サービスマネジメント", importance: 88, def: "Service Level Agreement。提供者と顧客が合意したサービス品質の目標。", tip: "稼働率99.9%など。SLO/SLIとセットで出ることも。", pair: null },
  { id: "audit", term: "システム監査", reading: "", field: "マネジメント", category: "システム監査", importance: 84, def: "情報システムが適切に整備・運用されているかを、独立した立場で点検・評価すること。", tip: "監査人は被監査部門から独立していることが重要。", pair: null },
  { id: "internalcontrol", term: "内部統制", reading: "ないぶとうせい", field: "マネジメント", category: "システム監査", importance: 80, def: "業務の有効性、財務報告の信頼性、法令遵守などを確保するための社内の仕組み。", tip: "チェックと牽制。IT全般統制も関連。", pair: null },
  { id: "riskavoid", term: "リスク回避", reading: "リスクかいひ", field: "マネジメント", category: "プロジェクトマネジメント", importance: 82, def: "リスクそのものを発生させないよう、計画や対象を変える対応。", tip: "危ない作業自体をやめる。", pair: "risktransfer" },
  { id: "risktransfer", term: "リスク転嫁", reading: "リスクてんか", field: "マネジメント", category: "プロジェクトマネジメント", importance: 82, def: "保険や外部委託などで、リスクの影響を他者に移す対応。", tip: "自分で持たない。低減・保有・回避とセット。", pair: "riskmitigate" },
  { id: "riskmitigate", term: "リスク低減", reading: "リスクていげん", field: "マネジメント", category: "プロジェクトマネジメント", importance: 80, def: "発生確率や影響度を下げる対策を講じる対応。", tip: "バックアップ、教育、冗長化など。", pair: "riskaccept" },
  { id: "riskaccept", term: "リスク保有", reading: "リスクほゆう", field: "マネジメント", category: "プロジェクトマネジメント", importance: 78, def: "対策コストが見合わない場合などに、リスクを認めたうえで受け入れる対応。", tip: " Contingency（万一の備え）を残すことも。", pair: "riskavoid" },

  // ===== ストラテジ系 =====
  { id: "dx", term: "DX", reading: "ディーエックス", field: "ストラテジ", category: "経営戦略", importance: 94, def: "Digital Transformation。デジタル技術で製品・サービス・業務を変革し、競争優位を築くこと。", tip: "単なるIT導入ではなく「変革」。", pair: "society50" },
  { id: "society50", term: "Society 5.0", reading: "ソサエティゴーテンゼロ", field: "ストラテジ", category: "企業活動", importance: 80, def: "サイバー空間と現実空間を高度に融合させた、人間中心の超スマート社会の構想。", tip: "狩猟→農耕→工業→情報に次ぐ第5の社会。", pair: "dx" },
  { id: "mvv", term: "MVV", reading: "ミッション・ビジョン・バリュー", field: "ストラテジ", category: "企業活動", importance: 78, def: "企業の存在意義（Mission）、目指す姿（Vision）、行動指針（Value）の組。", tip: "シラバス近年追加。パーパス経営と隣接。", pair: "purpose" },
  { id: "purpose", term: "パーパス経営", reading: "", field: "ストラテジ", category: "企業活動", importance: 74, def: "社会における存在意義を軸に、経営の方向性を定める考え方。", tip: "利益だけでなく「何のためにある会社か」。", pair: "mvv" },
  { id: "humancapital", term: "人的資本経営", reading: "じんてきしほんけいえい", field: "ストラテジ", category: "企業活動", importance: 76, def: "人材を「資本」と捉え、その価値を高めることへ投資して企業価値を上げる経営。", tip: "コストではなく投資。開示も進む。", pair: null },
  { id: "reskilling", term: "リスキリング", reading: "", field: "ストラテジ", category: "経営管理", importance: 82, def: "技術変化や事業転換に合わせて、新たなスキルを身につけ直すこと。", tip: "同じ会社で役割が変わる前提が多い。", pair: null },
  { id: "dei", term: "DE&I", reading: "ディーイーアンドアイ", field: "ストラテジ", category: "経営管理", importance: 74, def: "Diversity, Equity & Inclusion。多様性・公平性・包摂を組織運営に取り入れる考え方。", tip: "ただ集めるだけでなく、公平に機会を開き活かす。", pair: null },
  { id: "swot", term: "SWOT分析", reading: "スウォット", field: "ストラテジ", category: "経営戦略マネジメント", importance: 92, def: "強み・弱み（内部）と機会・脅威（外部）を整理し、戦略の方向を考える枠組み。", tip: "Strength, Weakness, Opportunity, Threat。", pair: "pest" },
  { id: "pest", term: "PEST分析", reading: "ペスト", field: "ストラテジ", category: "経営戦略マネジメント", importance: 80, def: "Politics・Economy・Society・Technologyの外部環境を眺める分析。", tip: "マクロ環境。SWOTの「機会・脅威」の材料。", pair: "swot" },
  { id: "ppm", term: "PPM", reading: "ピーピーエム", field: "ストラテジ", category: "経営戦略マネジメント", importance: 84, def: "Product Portfolio Management。花形・金のなる木・問題児・負け犬で事業を配置する。", tip: "市場成長率×相対シェア。資源配分に使う。", pair: null },
  { id: "pdca", term: "PDCA", reading: "ピーディーシーエー", field: "ストラテジ", category: "経営管理", importance: 90, def: "Plan-Do-Check-Act。計画し、実行し、評価し、改善するサイクル。", tip: "継続的改善の基本。OODAはより速い意思決定。", pair: "ooda" },
  { id: "ooda", term: "OODAループ", reading: "ウーダ", field: "ストラテジ", category: "経営管理", importance: 76, def: "Observe-Orient-Decide-Act。観察から行動までの速い意思決定サイクル。", tip: "変化の激しい環境向き。PDCAより回転が速い。", pair: "pdca" },
  { id: "bsc", term: "バランススコアカード", reading: "", field: "ストラテジ", category: "経営戦略マネジメント", importance: 78, def: "財務・顧客・内部プロセス・学習と成長の4視点で戦略を管理する手法。", tip: "財務だけ見ない。戦略マップとセット。", pair: null },
  { id: "outsourcing", term: "アウトソーシング", reading: "", field: "ストラテジ", category: "経営管理", importance: 80, def: "自社の業務の一部を外部企業に委託すること。", tip: "コア業務に集中する狙い。ロックインに注意。", pair: null },
  { id: "bcp", term: "BCP", reading: "ビーシーピー", field: "ストラテジ", category: "企業活動", importance: 88, def: "Business Continuity Plan。災害や障害時にも重要業務を続けるための計画。", tip: "復旧目標時間（RTO）と復旧時点（RPO）が頻出。", pair: "rto" },
  { id: "rto", term: "RTO", reading: "アールティーオー", field: "ストラテジ", category: "企業活動", importance: 80, def: "Recovery Time Objective。障害後、何時間以内に復旧したいかという目標時間。", tip: "「いつまでに戻すか」。RPOは「どの時点のデータまで戻すか」。", pair: "rpo" },
  { id: "rpo", term: "RPO", reading: "アールピーオー", field: "ストラテジ", category: "企業活動", importance: 80, def: "Recovery Point Objective。障害時に、どの時点までのデータ復旧を許容するか。", tip: "バックアップ間隔と直結。損失してよいデータ量の上限。", pair: "rto" },
  { id: "copyright", term: "著作権", reading: "ちょさくけん", field: "ストラテジ", category: "法務", importance: 92, def: "著作物を創作した時点で自動的に発生する権利。プログラムも対象。", tip: "登録不要。特許は出願・審査が必要。", pair: "patent" },
  { id: "patent", term: "特許権", reading: "とっきょけん", field: "ストラテジ", category: "法務", importance: 90, def: "発明を保護する産業財産権。出願し、審査を経て発生。存続期間は出願から原則20年。", tip: "新規性・進歩性などが要件。", pair: "utility" },
  { id: "utility", term: "実用新案権", reading: "じつようしんあんけん", field: "ストラテジ", category: "法務", importance: 76, def: "物品の形状・構造・組合せの考案を保護する権利。特許より簡易。", tip: "「小発明」。プログラム単体は対象外の整理が定番。", pair: "patent" },
  { id: "trademark", term: "商標権", reading: "しょうひょうけん", field: "ストラテジ", category: "法務", importance: 84, def: "商品やサービスを他社と区別するマークを保護する権利。", tip: "ロゴやブランド名。更新で実質無期限。", pair: "design" },
  { id: "design", term: "意匠権", reading: "いしょうけん", field: "ストラテジ", category: "法務", importance: 78, def: "物品のデザイン（形状・模様・色彩）を保護する権利。", tip: "見た目。産業財産権の4つをセットで。", pair: "trademark" },
  { id: "personalinfo", term: "個人情報保護法", reading: "", field: "ストラテジ", category: "法務", importance: 93, def: "個人情報の適正な取扱いを定めた法律。本人同意や安全管理措置が要点。", tip: "要配慮個人情報は本人同意が原則。", pair: null },
  { id: "unauthorized", term: "不正アクセス禁止法", reading: "", field: "ストラテジ", category: "法務", importance: 86, def: "他人のID・パスワードの無断利用や、セキュリティホールを突いた侵入などを禁じる法律。", tip: "「入ること」自体が罪。", pair: null },
  { id: "infoplat", term: "情報流通プラットフォーム対処法", reading: "", field: "ストラテジ", category: "法務", importance: 80, def: "大規模SNSなどへの削除対応義務などを定めた法律。旧プロバイダ責任制限法から再編。", tip: "シラバス6.4の更新ポイント。", pair: null },
  { id: "subcontract", term: "中小受託取引適正化法", reading: "ちゅうしょうじゅたくとりひきてきせいかほう", field: "ストラテジ", category: "法務", importance: 76, def: "下請法に代わり追加された、中小の受託取引を適正化するための法律。", tip: "シラバス6.5の変更点。名前を知っておく。", pair: null },
  { id: "poc", term: "PoC", reading: "ピーオーシー", field: "ストラテジ", category: "システム企画", importance: 78, def: "Proof of Concept。新しい技術やアイデアが実現可能かを、小さく検証すること。", tip: "本番導入の前の「概念実証」。", pair: null },
  { id: "roi", term: "ROI", reading: "アールオーアイ", field: "ストラテジ", category: "会計・財務", importance: 82, def: "Return On Investment。投資額に対してどれだけ利益が返ってきたかを見る指標。", tip: "利益÷投資額。高いほど効率が良い。", pair: "roa" },
  { id: "roa", term: "ROA", reading: "アールオーエー", field: "ストラテジ", category: "会計・財務", importance: 74, def: "Return On Assets。総資産を使ってどれだけ利益を生んだか。", tip: "資産効率。ROEは自己資本に対する利益。", pair: "roi" },
  { id: "plc", term: "製品ライフサイクル", reading: "", field: "ストラテジ", category: "経営戦略マネジメント", importance: 80, def: "導入期・成長期・成熟期・衰退期という製品の一生。段階で戦略が変わる。", tip: "成長期はシェア拡大、成熟期は差異化やコスト。", pair: "ppm" },
  { id: "css", term: "コアコンピタンス", reading: "", field: "ストラテジ", category: "経営戦略マネジメント", importance: 78, def: "他社が真似しにくく、顧客に価値を届ける中核的な能力。", tip: "「自社だけが本当に強いこと」。", pair: null },
  { id: "ea", term: "EA", reading: "エンタープライズアーキテクチャ", field: "ストラテジ", category: "システム戦略", importance: 76, def: "組織全体の業務とシステムを、設計図として体系的に整理する枠組み。", tip: "ビジネス・データ・アプリケーション・テクノロジの層。", pair: null },
  { id: "fitgap", term: "フィット&ギャップ分析", reading: "", field: "ストラテジ", category: "システム企画", importance: 74, def: "パッケージソフトと自社要件の一致（フィット）と差（ギャップ）を洗い出す分析。", tip: "カスタマイズ量の判断材料。", pair: null }
];
