// 英語略称 → 省略前の語。意味表示で使う。
window.ITPASS_EXPAND = {
  cpu: "Central Processing Unit",
  gpu: "Graphics Processing Unit",
  ram: "Random Access Memory",
  rom: "Read Only Memory",
  ssd: "Solid State Drive",
  hdd: "Hard Disk Drive",
  os: "Operating System",
  saas: "Software as a Service",
  paas: "Platform as a Service",
  iaas: "Infrastructure as a Service",
  lan: "Local Area Network",
  wan: "Wide Area Network",
  vlan: "Virtual LAN",
  vpn: "Virtual Private Network",
  tcpip: "Transmission Control Protocol / Internet Protocol",
  udp: "User Datagram Protocol",
  dns: "Domain Name System",
  http: "Hypertext Transfer Protocol / HTTP Secure",
  sql: "Structured Query Language",
  ddos: "Distributed Denial of Service",
  idsips: "Intrusion Detection System / Intrusion Prevention System",
  raid0: "Redundant Arrays of Inexpensive Disks 0",
  raid1: "Redundant Arrays of Inexpensive Disks 1",
  raid5: "Redundant Arrays of Inexpensive Disks 5",
  raid6: "Redundant Arrays of Inexpensive Disks 6",
  genai: "Generative Artificial Intelligence",
  iot: "Internet of Things",
  wbs: "Work Breakdown Structure",
  itil: "Information Technology Infrastructure Library",
  sla: "Service Level Agreement",
  dx: "Digital Transformation",
  mvv: "Mission / Vision / Value",
  dei: "Diversity, Equity & Inclusion",
  swot: "Strengths, Weaknesses, Opportunities, Threats",
  pest: "Politics, Economy, Society, Technology",
  ppm: "Product Portfolio Management",
  pdca: "Plan / Do / Check / Act",
  ooda: "Observe / Orient / Decide / Act",
  bcp: "Business Continuity Plan",
  rto: "Recovery Time Objective",
  rpo: "Recovery Point Objective",
  poc: "Proof of Concept",
  roi: "Return On Investment",
  roa: "Return On Assets",
  ea: "Enterprise Architecture",
  nas: "Network Attached Storage",
  san: "Storage Area Network",
  bios: "Basic Input/Output System",
  dma: "Direct Memory Access",
  utf8: "Unicode Transformation Format-8",
  api: "Application Programming Interface",
  sdk: "Software Development Kit",
  html: "HyperText Markup Language",
  csslang: "Cascading Style Sheets",
  json: "JavaScript Object Notation",
  xml: "eXtensible Markup Language",
  rest: "Representational State Transfer",
  smtp: "Simple Mail Transfer Protocol",
  pop: "Post Office Protocol",
  imap: "Internet Message Access Protocol",
  dhcp: "Dynamic Host Configuration Protocol",
  nat: "Network Address Translation",
  mac: "Media Access Control",
  ipaddr: "Internet Protocol",
  ipv6: "Internet Protocol version 6",
  waf: "Web Application Firewall",
  sqli: "SQL Injection",
  csrf: "Cross-Site Request Forgery",
  rbac: "Role-Based Access Control",
  aes: "Advanced Encryption Standard",
  rsa: "Rivest–Shamir–Adleman",
  pki: "Public Key Infrastructure",
  wpa3: "Wi-Fi Protected Access 3",
  ssid: "Service Set Identifier",
  byod: "Bring Your Own Device",
  mdm: "Mobile Device Management",
  edr: "Endpoint Detection and Response",
  bi: "Business Intelligence",
  rag: "Retrieval-Augmented Generation",
  rfid: "Radio Frequency Identification",
  ar: "Augmented Reality",
  vr: "Virtual Reality",
  acid: "Atomicity, Consistency, Isolation, Durability",
  nosql: "Not only SQL",
  mtbf: "Mean Time Between Failures",
  mttr: "Mean Time To Repair",
  cab: "Change Advisory Board",
  ciitem: "Configuration Item",
  cmdb: "Configuration Management Database",
  cobit: "Control Objectives for Information and Related Technologies",
  sox: "Sarbanes–Oxley Act（日本版内部統制）",
  devops: "Development and Operations",
  cicd: "Continuous Integration / Continuous Delivery",
  csr: "Corporate Social Responsibility",
  esg: "Environment, Social, Governance",
  sdgs: "Sustainable Development Goals",
  kpi: "Key Performance Indicator",
  kgi: "Key Goal Indicator",
  csf: "Critical Success Factor",
  stp: "Segmentation, Targeting, Positioning",
  crm: "Customer Relationship Management",
  scm: "Supply Chain Management",
  erp: "Enterprise Resource Planning",
  jit: "Just In Time",
  abcanalysis: "ABC analysis",
  tco: "Total Cost of Ownership",
  rfi: "Request For Information",
  rfp: "Request For Proposal",
  rfq: "Request For Quotation",
  bpo: "Business Process Outsourcing",
  isms: "Information Security Management System",
  iso9001: "International Organization for Standardization 9001（品質）",
  iso14001: "International Organization for Standardization 14001（環境）",
  b2b: "Business to Business",
  b2c: "Business to Consumer",
  c2c: "Consumer to Consumer",
  edi: "Electronic Data Interchange",
  sor: "System of Record",
  soe: "System of Engagement",
  mvp: "Minimum Viable Product",
  ux: "User Experience",
  ui: "User Interface",
  seo: "Search Engine Optimization",
  npv: "Net Present Value",
  evm: "Earned Value Management",
  pv: "Planned Value",
  ev: "Earned Value",
  ac: "Actual Cost",
  and: "AND",
  orop: "OR",
  xor: "XOR (exclusive OR)",
  notop: "NOT",
  itgov: "IT Governance"
};

window.expandOf = function (item) {
  if (!item) return "";
  if (item.full) return item.full;
  return (window.ITPASS_EXPAND && window.ITPASS_EXPAND[item.id]) || "";
};
